In [18]:
import pandas as pd
import pickle
import re
from nltk.stem import RSLPStemmer
from nltk.corpus import stopwords

In [50]:
df2= pd.read_csv('olist_preprocessadoT.csv')
df2=df2['review']

In [51]:
df2.to_list()

['receber bem antar prazo estipular',
 'parabém loja lannister adorar comprar internet segurar prático parabém todo feliz páscoa',
 'recomendar aparelhar eficiente site marcar aparelhar impresso desinfector chegar outro nome atualizar marcar corretar vez aparelhar',
 'pouco travar valor ta bom',
 'super recomendar vendedor confiável produto ok entregar antar prazo',
 'gostar saber sempre receber comprar agora decpcionou',
 'não chegar produto mau',
 'ótimo loja noto',
 'obrigar atençao amim dispensar',
 'comprar realizar facilmente entregar efetuada antar prazo dar produto começar ser usar presentar problema',
 'relógio bonito baratar',
 'não gostar comprar gatar lebre',
 'sempre comprar internet entregar ocorrer antar prazo combinar acreditar ser prazo máximo stark prazo máximo esgotar ainda não receber produto',
 'bom receber exatamente esperar demais encomendar outro vendedor atrasar chegar prazo',
 'bom recomendar',
 'bom',
 'maravilhoso tô completamente apaixonar loja super respon

In [54]:
def re_breakline(text_list):
    return [re.sub('[\n\r]', ' ', r) for r in text_list]
reviews = list(df2.values)
reviews_breakline = re_breakline(reviews)
#df2['review'] = reviews_breakline


In [55]:
def re_hiperlinks(text_list):
    pattern = 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'
    return [re.sub(pattern, ' link ', r) for r in text_list]
reviews_hiperlinks = re_hiperlinks(reviews_breakline)
#df2['review'] = reviews_hiperlinks

In [56]:
        #st.write('dates')
def re_dates(text_list):
    pattern = '([0-2][0-9]|(3)[0-1])(\/|\.)(((0)[0-9])|((1)[0-2]))(\/|\.)\d{2,4}'
    return [re.sub(pattern, ' data ', r) for r in text_list]
reviews_dates = re_dates(reviews_breakline)
#df2['review'] = reviews_dates
        #st.write(df2)
        #st.write('money')


In [57]:
def re_money(text_list):
    pattern = '[R]{0,1}\$[ ]{0,}\d+(,|\.)\d+'
    return [re.sub(pattern, ' dinheiro ', r) for r in text_list]
reviews_money = re_money(reviews_dates)
#df2['review'] = reviews_money
        #st.write(df2)


In [58]:

        #st.write('numbers')
def re_numbers(text_list):
    return [re.sub('[0-9]+', ' numero ', r) for r in text_list]
#reviews_numbers = re_numbers(reviews_money)
        #st.write(df2)


In [59]:

        #st.write('negation')
def re_negation(text_list):
    return [re.sub('([nN][ãÃaA][oO]|[ñÑ]| [nN] )', ' negação ', r) for r in text_list]
reviews_negation = re_negation(reviews_numbers)
        #st.write(df2)

        #st.write('special chars')
def re_special_chars(text_list):
    return [re.sub('\W', ' ', r) for r in text_list]
reviews_special_chars = re_special_chars(reviews_negation)
#df2['review'] = reviews_special_chars
        #st.write(df2)

        #st.write('white space')
def re_whitespaces(text_list):
    white_spaces = [re.sub('\s+', ' ', r) for r in text_list]
    white_spaces_end = [re.sub('[ \t]+$', '', r) for r in white_spaces]
    return white_spaces_end
reviews_whitespaces = re_whitespaces(reviews_special_chars)
#df2['review'] = reviews_whitespaces
        #st.write(df2)

        #st.write('remoçao stopwords e caixa baixa')
def stopwords_removal(text, cached_stopwords=stopwords.words('portuguese')):
    return [c.lower() for c in text.split() if c.lower() not in cached_stopwords]
reviews_stopwords = [' '.join(stopwords_removal(review)) for review in reviews_whitespaces]
#df2['review'] = reviews_stopwords
        #st.write(df2)

        #st.write('Função para remover o stopwords e stemmer')
def stemming_process(text, stemmer=RSLPStemmer()):
    return [stemmer.stem(c) for c in text.split()]
reviews_stemmer = [' '.join(stemming_process(review)) for review in reviews_stopwords]
#df2['review'] = reviews_stemmer

In [60]:
modelo = pickle.load(open('modelo.pkl','rb'))

In [63]:
y_predict = modelo.predict(df2)

In [64]:
y_predict

array([1, 1, 1, ..., 0, 1, 1], dtype=int64)

In [67]:
import numpy as np

In [68]:
unique, counts = np.unique(y_predict, return_counts= True)
result = np.column_stack((unique, counts)) 
print (result)

[[    0  7625]
 [    1 34504]]


In [72]:
result[0]

array([   0, 7625], dtype=int64)

In [84]:
for b in result[0]>result[1]:
    if b:
        print("😖😫😩" "Conteúdo negativo")
    else:
        print('😃😄😁" "Conteúdo positivo')

😃😄😁" "Conteúdo positivo
😃😄😁" "Conteúdo positivo
